-- Track who created a sales lead (actor) vs who owns it (user_id).
-- This supports: "Lead generated by which sales personnel" visibility across machines.

alter table if exists public.leads
  add column if not exists created_by_user_id text,
  add column if not exists created_by_name text;

update public.leads
set created_by_user_id = user_id
where created_by_user_id is null;

create index if not exists leads_created_by_user_id_idx on public.leads (created_by_user_id);
